### ISSUE TITLE
Mob-objects returned by mcl_mobs.spawn() is bugging

### ISSUE THREAD

**Issue by YoManGaming** [esaworks/satlantis_game#2]
When i try to spawn a mob with mcl_mobs.spawn(), the object it returns doesnt update when i do something with the mob. It doesnt change the pos where the mob is at, set_nametag doesnt work, health doesnt update etc. Is there any way to fix this?

**Comment by esaworks** [comment]
Which parameters you tried with this function. FYI at current stage of this mod: 
- There are only 3 mobs spawnable -> mobs_mc:zombie, mobs_mc:spider, mobs_mc:skeleton. 
- I tried mcl_mobs.spawn(pos,id) function by directly replacing it minetest.add_entity(pos, mob) function which is called within **on_place** event of an egg. Seems like working at my side. 

So, It helps if you can elaborate how to reproduce this issue. Thanks.

**Comment by YoManGaming** [comment]
I tried to spawn more than the mobs you mentioned so maybe that could be the issue. Any way to fix this for the other mobs?

**Comment by esaworks** [comment]
I intentionally disabled other mobs on request. So, if you want to test this for other mobs, you need to locally enable the codes I disabled and test it that way. Or just spawn those 3 mobs when you work on your part.

**Comment by esaworks** [comment]
This issue is solved by @YoManGaming with PR #1

**Comment by esaworks** [comment]
This issue is solved by @YoManGaming with PR #1
